export const CHANGE_PAGE1 = 'CHANGE_PAGE1';
export const CHANGE_PAGE2 = 'CHANGE_PAGE2';

export const CHANGE_PAGE1_ASYNC = 'CHANGE_PAGE1_ASYNC';

export const REQUEST_VISITED_RESTOS = "REQUEST_VISITED_RESTOS_REQUEST";

export const RECEIVE_VISITED_RESTOS = "RECEIVE_VISITED_RESTOS_REQUEST";
