export const CHANGE_PAGE1 = 'CHANGE_PAGE1';
export const CHANGE_PAGE2 = 'CHANGE_PAGE2';

export const CHANGE_PAGE1_ASYNC = 'CHANGE_PAGE1_ASYNC';

export const REQUEST_VISITED_RESTOS = "REQUEST_VISITED_RESTOS";
export const RECEIVE_VISITED_RESTOS = "RECEIVE_VISITED_RESTOS";

export const REQUEST_ALL_RESTOS = "REQUEST_ALL_RESTOS";
export const RECEIVE_ALL_RESTOS = "RECEIVE_ALL_RESTOS";

export const CHECKED = "CHECKED";
export const POSTED_SUCCESS = "POSTED_SUCCESS";


export const REQUEST_SEARCHED_RESTOS = 'REQUEST_SEARCHED_RESTOS';
export const REQUEST_SEARCHED_NAME_RESTOS = 'REQUEST_SEARCHED_NAME_RESTOS';
export const REQUEST_SEARCHED_TYPE_RESTOS = 'REQUEST_SEARCHED_TYPE_RESTOS';

export const RECEIVE_SEARCHED_RESTOS = 'RECEIVE_SEARCHED_RESTOS';

export const SHOW_ALL_RESTAURANTS = 'SHOW_ALL_RESTAURANTS';export const SHOW_SEARCHED_RESTAURANTS = 'SHOW_SEARCHED_RESTAURANTS';

export const PAGINATION_NUMBER = 'PAGINATION_NUMBER';

export const LOADING = 'LOADING';

export const SHOW_ERROR = 'SHOW_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
